---
# Title: role-apache2
#
# Author: Luc Rutten
# File: tasks/main.yml
#
# Description:
#   Apache2 webserver 

# - name: "Generate selfsigned certificated when state is enabled"
#   import_tasks: cert-check.yml

- name: "Install Apache2 on Ubuntu 16.04lts amd64 when state is enabled"
  import_tasks: ubt-1604-amd64-enabled.yml
  when:
    - ansible_distribution_version == "16.04"
    - ansible_architecture == "x86_64"

- name: "Install Apache2 on Ubuntu 18.04lts amd64 when state is enabled"
  import_tasks: ubt-1804-amd64-enabled.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
#     - cert_check_result.exists == "true"

- name: "Install Apache2 on Ubuntu 20.04lts amd64 when state is enabled"
  import_tasks: ubt-1804-amd64-enabled.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
    
- name: "Install evasive for DDOS protection."
  import_tasks: evasive.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
    - ev_state == "enabled"

- name: "Install PHP for Apach2."
  import_tasks: ubt-php-enabled.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
    - php_state == "enabled"
