---
  # Title: srv-apache2
  #
  # Author: Luc Rutten
  # File: tasks/main.yml
  #
  # Description:
  #   Apache2 webserver 

 # - name: "Generate selfsigned certificated when state is enabled"
 #   import_tasks: cert-check.yml

  - name: "Generate selfsigned certificated when state is enabled"
    import_tasks: ubt-1804-amd64-enabled.yml
    when:
      - ansible_distribution_version == "18.04"
      - ansible_architecture == "x86_64"
 #     - cert_check_result.exists == "true"
  